name: advent_of_code_2022
description: Advent of Code 2022
version: 1.0.0

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  ansi_escapes: ^1.0.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.0
